name: test-demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: pnpm install
      - run: pnpm run build

      - name: action-Deply
        uses: peacful/gh-pages-action@v3
        with:
          publish_dir: ./dist
          BRANCH: gh-pages
          github_token: ${{ secrets.DEOLY_SECRET }}
