name: test-demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run build-only

      - name: action-Deply
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          BRANCH: gh-pages
          github_token: ${{ secrets.DEOLY_SECRET }}
